name: wind-science
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.6
  - numpy==1.23.4
  - pandas==1.5.0
  - xarray==2023.9.0
  - netCDF4==1.6.1
  - cartopy==0.23.0
  - cmocean==2.0
  - windrose==1.9.0
  - geographiclib==2.0
  - wrf-python==1.3.4.1
  - pynio==1.5.5
  - erddapy==1.2.1
  - cool_maps==1.0.1
  - matplotlib==3.8.0
  - geopandas==0.14.0